/*

ONLY CHANGE THE FOLLOWING VARIABLES:
------------------------------------

AVAILABLE: If a page in the blueprint is blank (e.g. there are no
Customs on page 5), mark available as false; otherwise, it should
be true. (If false: width, height, and imgFolder don't matter; the
system will use the 'unavailable' folder/img.)

WIDTH & HEIGHT: The width and height of the original jpg/png file in
pixels. These must be exact for the system to work properly!

IMGFOLDER: Name/Location of folder generated by Zoomify.

*/

var pages = {
  page1: {
    available: true,
    width: 22200,
    height: 24000,
    imgFolder: "./img/page01v1/",
  },
};
